services:
  app:
    image: ghcr.io/fyyhub/lens:latest
    container_name: lens
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${LENS_PORT:-3000}:${LENS_PORT:-3000}"
    volumes:
      - ./data:/app/data
